const url=import.meta.env.VITE_SUPABASE_URL?.replace(/\/$/,'');const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
export const configured=!!url&&!!key;
const sessionKey='caderno-auth-session';
let session:any;try{session=JSON.parse(localStorage.getItem(sessionKey)||'null')}catch{session=null}
function setSession(s:any){session=s;try{if(s)localStorage.setItem(sessionKey,JSON.stringify(s));else localStorage.removeItem(sessionKey)}catch{}window.dispatchEvent(new Event('caderno-session'));}
export const signedIn=()=>!!session?.access_token;
async function auth(path:string,body:object){if(!configured)throw Error('Configure as variáveis do Supabase no Vercel.');const r=await fetch(url+'/auth/v1/'+path,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.msg||d.message||d.error_description||'Não foi possível entrar.');return d;}
export async function login(email:string,password:string){setSession(await auth('token?grant_type=password',{email,password}));}
let refreshing:Promise<any>|null=null;
async function token(){if(!signedIn())throw Error('Entre no caderno para continuar.');if(session.expires_at*1000<Date.now()+60000){refreshing??=auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token}).then(s=>{setSession(s);return s}).catch(e=>{setSession(null);throw e}).finally(()=>{refreshing=null});await refreshing;}return session.access_token;}
export async function logout(){try{const t=await token();await fetch(url+'/auth/v1/logout',{method:'POST',headers:{apikey:key,Authorization:'Bearer '+t}})}finally{setSession(null)}}
async function rest(path:string,options:RequestInit={}){const t=await token();const r=await fetch(url+'/rest/v1/'+path,{...options,headers:{apikey:key,Authorization:'Bearer '+t,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.message||'Não foi possível salvar ou carregar os dados.');}return r;}
export async function cloudFetch(_path:string,options:RequestInit={}){try{if(options.method==='POST'){const item=JSON.parse(options.body as string);await rest('records?on_conflict=owner,id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:item.id,owner:session?.user?.id,kind:item.kind,data:item})});return Response.json({ok:true});}const records:any[]=[];for(let offset=0;;offset+=1000){const r=await rest('records?select=data&order=id&limit=1000&offset='+offset);const page=await r.json();records.push(...page.map((x:any)=>x.data));if(page.length<1000)break;}return Response.json({records});}catch(e:any){return Response.json({error:e.message},{status:400});}}
export async function exportRecords(){const r=await cloudFetch('');const d=await r.json();if(!r.ok)throw Error(d.error);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,records:d.records},null,2)],{type:'application/json'}));a.download='caderno-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
export async function importRecords(file:File){const raw=JSON.parse(await file.text());const rows=Array.isArray(raw)?raw:raw.records;if(!Array.isArray(rows)||rows.length>20000)throw Error('Backup inválido.');const order=['class','student','lesson','activity','schedule','event','assessment','grade','weekly'];let count=0;for(const item of [...rows].sort((a,b)=>order.indexOf(a.kind)-order.indexOf(b.kind))){const r=await cloudFetch('',{method:'POST',body:JSON.stringify(item)});if(!r.ok){const d=await r.json();throw Error(`${count} registros importados. Erro: ${d.error}. Você pode repetir a importação sem duplicar os registros.`);}count++;}return count;}
