"use client";
import {useState} from 'react';
import {ChevronLeft,ChevronRight} from 'lucide-react';
import {toast} from 'sonner';
import {dateKey} from './monthly-calendar';
type Entry={id:string;kind:string;[key:string]:any};
export function mondayKey(value:string){const d=new Date(value+'T12:00:00');d.setDate(d.getDate()-((d.getDay()+6)%7));return dateKey(d);}
export function shiftWeek(value:string,amount:number){const d=new Date(value+'T12:00:00');d.setDate(d.getDate()+amount*7);return dateKey(d);}
export default function WeeklyJournal({records,classes,filter,onSave}:{records:Entry[];classes:Entry[];filter:string;onSave:(r:Entry)=>Promise<void>}){
const [week,setWeek]=useState(()=>mondayKey(dateKey(new Date()))),[drafts,setDrafts]=useState<Record<string,string>>({}),[saving,setSaving]=useState<string|null>(null);
const end=new Date(week+'T12:00:00');end.setDate(end.getDate()+4);
const display=(v:string)=>new Date(v+'T12:00:00').toLocaleDateString('pt-BR');const visible=classes.filter(c=>filter==='all'||filter===c.id);
return <><section className="panel journalheading"><div><p className="eyebrow">REGISTRO DA SEMANA</p><h2>{display(week)} a {display(dateKey(end))}</h2><p className="muted">Descreva brevemente o que foi trabalhado em cada turma.</p></div><div className="weekcontrols"><button aria-label="Semana anterior" onClick={()=>setWeek(shiftWeek(week,-1))}><ChevronLeft size={18}/></button><label className="field">Semana de<input type="date" aria-label="Selecionar semana" value={week} onChange={e=>{if(e.target.value)setWeek(mondayKey(e.target.value))}}/></label><button aria-label="Próxima semana" onClick={()=>setWeek(shiftWeek(week,1))}><ChevronRight size={18}/></button><button onClick={()=>setWeek(mondayKey(dateKey(new Date())))}>Semana atual</button></div></section><div className="cards">{visible.map(c=>{const id=`weekly:${week}:${c.id}`;const record=records.find(r=>r.kind==='weekly'&&r.classId===c.id&&r.week===week);const value=drafts[id]??record?.content??'';const changed=drafts[id]!==undefined&&drafts[id]!==record?.content;return <section className="panel journalcard" key={id}><p className="eyebrow">{c.school||c.subject||'Turma'}</p><h2>{c.title}</h2><label className="field">Resumo da semana<textarea rows={5} placeholder="Ex.: Trabalhamos a crise do Primeiro Reinado, corrigimos os exercícios e iniciamos a revisão para a prova." value={value} onChange={e=>setDrafts({...drafts,[id]:e.target.value})}/></label><div className="cardfoot"><span className="muted">{changed?'Alterações não salvas':record?'Resumo salvo':'Ainda sem registro'}</span><button className="primary" disabled={saving===id||!value.trim()||!changed} onClick={async()=>{setSaving(id);try{await onSave({id,kind:'weekly',classId:c.id,week,title:`Semanário · ${c.title}`,content:value});setDrafts(d=>{const next={...d};delete next[id];return next});toast.success('Resumo semanal salvo')}catch(e:any){toast.error(e.message)}finally{setSaving(null)}}}>{saving===id?'Salvando…':'Salvar resumo'}</button></div></section>})}{!visible.length&&<div className="empty"><h3>Cadastre uma turma para começar</h3><p>Cada turma terá seu próprio resumo semanal, com histórico das semanas anteriores.</p></div>}</div></>;
}
