"use client";
import {cloudFetch} from "../cloud";
import {useEffect,useState} from "react";
import {BookOpen,Plus,Users,CalendarDays,ClipboardList,GraduationCap,CheckCircle2,Pencil} from "lucide-react";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import WeeklyJournal from "./weekly-journal";
import {Checkbox} from "@/components/ui/checkbox";
import MonthlyCalendar, {dateKey} from "./monthly-calendar";
import {Toaster,toast} from "sonner";
type RecordItem={id:string;kind:string;[key:string]:any};
const sections=[['overview','Visão geral',BookOpen],['class','Turmas',Users],['lesson','Planos de aula',CalendarDays],['weekly','Semanário',ClipboardList],['activity','Atividades',ClipboardList],['assessment','Avaliações e notas',GraduationCap]] as const;
const names: {[key:string]:string}={class:'turma',student:'aluno',lesson:'plano de aula',activity:'atividade',assessment:'avaliação',schedule:'horário de aula',event:'evento extra'};
function Picker({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:[string,string][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>}
const weekdays=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];
const schooldays=weekdays.slice(0,5);
const date=(d:string)=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'Sem data';
export default function Workspace(){
const [rows,setRows]=useState<RecordItem[]>([]),[tab,setTab]=useState('overview'),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[edit,setEdit]=useState<RecordItem|null>(null),[saving,setSaving]=useState(false),[gradeDraft,setGradeDraft]=useState<{[key:string]:string}>({});
async function load(){setLoading(true);try{const r=await cloudFetch('/api/records');const d:any=await r.json();if(!r.ok)throw Error(d.error);setRows(d.records);setError('');}catch(e:any){setError(e.message)}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
useEffect(()=>{const mc=(document as any).modelContext;if(!mc)return;const ac=new AbortController();try{Promise.resolve(mc.registerTool({name:'navigate_teacher_workspace',description:'Abre a seção do organizador docente, sem criar ou alterar registros.',inputSchema:{type:'object',properties:{section:{type:'string',enum:sections.map(x=>x[0])}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(!sections.some(s=>s[0]===input.section))throw Error('Seção inválida');setTab(input.section);return {section:input.section}}},{signal:ac.signal})).catch(()=>{})}catch{}return ()=>ac.abort()},[]);
const classes=rows.filter(r=>r.kind==='class');const visible=(kind:string)=>rows.filter(r=>r.kind===kind&&(filter==='all'||r.classId===filter||(['lesson','activity'].includes(r.kind)&&(r.classIds||[r.classId]).includes(filter))||r.id===filter));
const cls=(id:string)=>classes.find(c=>c.id===id)?.title||'Turma';
function start(kind:string,item?:RecordItem,day?:string){setEdit(item?{...item,...(['lesson','activity'].includes(kind)?{classIds:item.classIds||[item.classId],...(kind==='activity'?{requestedDate:item.requestedDate||item.date,dueDate:item.dueDate||''}:{})}:{})}:{id:crypto.randomUUID(),kind,title:'',classIds:['lesson','activity'].includes(kind)?[filter==='all'?classes[0]?.id||'':filter].filter(Boolean):undefined,classId:filter==='all'?(kind==='event'?'':classes[0]?.id||''):filter,date:day||dateKey(new Date()),...(kind==='activity'?{requestedDate:day||dateKey(new Date()),dueDate:''}:{}),status:'Planejada',day:'0',start:'07:00',end:'07:50',active:'Sim',year:'2026',term:'4º bimestre',max:'10',weight:'1'});}
async function persist(item:RecordItem){const res=await cloudFetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});const d:any=await res.json();if(!res.ok)throw Error(d.error);setRows(r=>[...r.filter(x=>x.id!==item.id),item]);}
async function save(e:React.FormEvent){e.preventDefault();if(!edit)return;setSaving(true);try{await persist(edit.kind==='activity'?{...edit,date:edit.requestedDate}:edit);setEdit(null);toast.success('Registro salvo');}catch(e:any){toast.error(e.message)}finally{setSaving(false)}}
function field(key:string,label:string,type='text',required=false){return <label className="field">{label}<input type={type} required={required} value={edit?.[key]??''} min={type==='number'?0.01:undefined} step={type==='number'?'any':undefined} onChange={e=>setEdit(v=>v?{...v,[key]:e.target.value}:v)}/></label>}
const upcoming=rows.filter(r=>['lesson','activity','assessment'].includes(r.kind)&&r.date>=new Date().toLocaleDateString('en-CA')&&r.status!=='Aplicada').sort((a,b)=>a.date.localeCompare(b.date));
const schedule=visible('schedule').filter(r=>r.active!=='Não'&&Number(r.day)<5).sort((a,b)=>a.start.localeCompare(b.start));
const times=[...new Set(schedule.map(r=>r.start))].sort();
const students=visible('student').sort((a,b)=>a.title.localeCompare(b.title));const assessments=visible('assessment');
function average(student:RecordItem,term:string){let numerator=0,denominator=0;rows.filter(r=>r.kind==='assessment'&&r.classId===student.classId&&r.term===term).forEach(a=>{const g=rows.find(r=>r.kind==='grade'&&r.studentId===student.id&&r.assessmentId===a.id);if(g){numerator+=Number(g.value)/Number(a.max)*10*Number(a.weight);denominator+=Number(a.weight)}});return denominator?(numerator/denominator).toFixed(1):'—'}
return <div className="shell"><Toaster richColors/><header className="masthead"><div className="brand"><span className="brandmark"><BookOpen size={23}/></span><div><strong>Caderno Docente</strong><small>SEU ESPAÇO DE ORGANIZAÇÃO</small></div></div><span className="private">Espaço pessoal · acesso restrito</span></header><main><div className="intro"><div><p className="eyebrow">ROTINA DOCENTE</p><h1>{sections.find(s=>s[0]===tab)?.[1]}</h1><p className="sub">Planeje, registre e acompanhe suas aulas.</p></div><div className="controls"><Picker label="Filtrar turma" value={filter} onChange={setFilter} options={ [['all','Todas as turmas'],...classes.map(c=>[c.id,c.title] as [string,string])] }/>{!['overview','weekly'].includes(tab)&&<button className="primary" onClick={()=>start(tab)} disabled={tab!=='class'&&!classes.length}><Plus size={18}/> {tab==='assessment'?'Nova avaliação':tab==='class'?'Nova turma':tab==='lesson'?'Novo plano':'Nova atividade'}</button>}</div></div>
<Tabs value={tab} onValueChange={setTab}><TabsList className="nav" variant="line">{sections.map(([v,t,Icon])=><TabsTrigger key={v} value={v}><Icon size={18}/>{t}</TabsTrigger>)}</TabsList></Tabs>
{loading?<div className="empty">Carregando seus registros…</div>:error?<div className="empty" role="alert"><p>{error}</p><button onClick={load}>Tentar novamente</button></div>:<>
{tab==='overview'&&<><section className="panel timetable"><div className="sectionhead"><div><p className="eyebrow">SEMANA DE AULAS</p><h2>Meus horários</h2></div><button className="primary" disabled={!classes.length} onClick={()=>start('schedule')}><Plus size={18}/> Adicionar horário</button></div>{schedule.length?<div className="tablewrap"><Table className="weeklytable"><TableHeader><TableRow><TableHead>Horário</TableHead>{schooldays.map((d,i)=><TableHead key={d} className={i===(new Date().getDay()+6)%7?'today':''}>{d}</TableHead>)}</TableRow></TableHeader><TableBody>{times.map(time=><TableRow key={time}><TableCell className="hourcell">{time}</TableCell>{schooldays.map((d,i)=><TableCell key={d} className="daycell">{schedule.filter(r=>r.start===time&&Number(r.day)===i).map(r=>{const c=classes.find(c=>c.id===r.classId);return <button key={r.id} className="schedulelesson" onClick={()=>start('schedule',r)} aria-label={'Editar horário: '+r.title+', '+d+' às '+r.start}><span>{r.start}–{r.end}</span><strong>{cls(r.classId)}</strong><small>{r.title}</small>{c?.school&&<small>{c.school}</small>}{r.room&&<small>{r.room}</small>}</button>})}</TableCell>)}</TableRow>)}</TableBody></Table></div>:<div className="empty"><CalendarDays/><h3>Monte seu quadro semanal</h3><p>{classes.length?'Adicione o dia da semana, a turma e os horários de início e fim.':'Cadastre uma turma para começar a montar seus horários.'}</p>{!classes.length&&<button className="primary" onClick={()=>start('class')}>Cadastrar turma</button>}</div>}<p className="footnote">Horários fixos que se repetem a cada semana. Clique em uma aula para editar.</p>{visible('schedule').some(r=>r.active==='Não')&&<details className="archived"><summary>Horários desativados</summary>{visible('schedule').filter(r=>r.active==='Não').map(r=><button className="textbutton" key={r.id} onClick={()=>start('schedule',r)}>{weekdays[Number(r.day)]} · {r.start}–{r.end} · {cls(r.classId)}</button>)}</details>}</section><div className="stats">{[['Turmas',classes.length],['Atividades aplicadas',visible('activity').filter(r=>r.status==='Aplicada').length],['Avaliações',assessments.length]].map(([t,n])=><div className="stat" key={t}><span>{t}</span><strong>{n}</strong></div>)}</div><MonthlyCalendar records={rows} classes={classes} filter={filter} onAdd={(kind,day)=>start(kind,undefined,day)} onEdit={r=>start(r.kind,r)}/></>}
{tab==='class'&&<><div className="cards">{visible('class').map(c=><section className="panel classcard" key={c.id}><div className="sectionhead"><span className="eyebrow">{c.subject||'Disciplina'}</span><button aria-label={'Editar '+c.title} onClick={()=>start('class',c)}><Pencil size={17}/></button></div><h2>{c.title}</h2><p>{c.school||'Sem escola informada'} · {c.year||'2026'}</p><div className="cardfoot"><span>{rows.filter(r=>r.kind==='student'&&r.classId===c.id).length} alunos</span><button className="textbutton" onClick={()=>{setFilter(c.id);start('student',{id:crypto.randomUUID(),kind:'student',title:'',classId:c.id})}}><Plus size={16}/> Aluno</button></div></section>)}</div>{!classes.length&&<div className="empty"><Users/><h3>Cadastre suas turmas</h3><p>Use a escola e a disciplina para organizar também as aulas particulares.</p><button className="primary" onClick={()=>start('class')}>Nova turma</button></div>}{students.length>0&&<section className="panel"><h2>Alunos {filter!=='all'?'· '+cls(filter):''}</h2><div className="studentlist">{students.map(s=><button key={s.id} onClick={()=>start('student',s)}><span>{s.title}<small>{cls(s.classId)}</small></span><Pencil size={16}/></button>)}</div></section>}</>}
{['lesson','activity'].includes(tab)&&<div className="cards">{visible(tab).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(r=><section className="panel recordcard" key={r.id}><div className="sectionhead"><span className="eyebrow">{date(r.kind==='activity'?(r.requestedDate||r.date):r.date)}</span><span className={'badge '+(r.status==='Aplicada'?'done':'')}>{r.status}</span></div><h2>{r.title}</h2><p className="muted">{['lesson','activity'].includes(r.kind)?(r.classIds||[r.classId]).map((id:string)=>cls(id)).join(' · '):cls(r.classId)}</p>{r.kind==='activity'&&<div className="activitydates"><span><strong>Solicitação</strong>{date(r.requestedDate||r.date)}</span><span><strong>Entrega</strong>{r.dueDate?date(r.dueDate):'Não definida'}</span></div>}{tab==='lesson'&&r.objectives&&<p><strong>Objetivos</strong><br/>{r.objectives}</p>}<p className="preserve">{r.content}</p>{r.notes&&<div className="notebox"><strong>Observações</strong><p>{r.notes}</p></div>}<div className="cardfoot"><button className="textbutton" onClick={()=>start(tab,r)}><Pencil size={16}/> Editar</button>{r.status!=='Aplicada'&&<button className="textbutton" onClick={()=>persist({...r,status:'Aplicada'}).then(()=>toast.success('Aplicação registrada')).catch(e=>toast.error(e.message))}><CheckCircle2 size={16}/> Marcar aplicada</button>}</div></section>)}{!visible(tab).length&&<div className="empty"><ClipboardList/><h3>{tab==='lesson'?'Nenhum plano nesta turma':'Nenhuma atividade registrada'}</h3><p>{classes.length?'Use o botão acima para criar o primeiro registro.':'Cadastre uma turma para começar.'}</p></div>}</div>}
{tab==='weekly'&&<WeeklyJournal records={rows} classes={classes} filter={filter} onSave={persist}/>}
{tab==='assessment'&&<>{!assessments.length&&<div className="empty"><GraduationCap/><h3>Da avaliação ao acompanhamento</h3><p>Cadastre turmas e alunos; crie uma avaliação para lançar as notas.</p></div>}{assessments.map(a=><section className="panel assessment" key={a.id}><div className="sectionhead"><div><p className="eyebrow">{cls(a.classId)} · {a.term}</p><h2>{a.title}</h2><p className="muted">{date(a.date)} · Valor: {a.max} · Peso: {a.weight}</p></div><button className="textbutton" onClick={()=>start('assessment',a)}><Pencil size={16}/> Editar</button></div>{a.content&&<p>{a.content}</p>}<div className="tablewrap"><Table><TableHeader><TableRow><TableHead>Aluno</TableHead><TableHead>Nota / {a.max}</TableHead><TableHead>Média do período / 10</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{rows.filter(s=>s.kind==='student'&&s.classId===a.classId).sort((a,b)=>a.title.localeCompare(b.title)).map(s=>{const id=a.id+':'+s.id;const g=rows.find(g=>g.kind==='grade'&&g.id===id);return <TableRow key={s.id}><TableCell>{s.title}</TableCell><TableCell><input className="grade" aria-label={'Nota de '+s.title+' em '+a.title} type="number" min="0" max={a.max} step="0.1" placeholder="—" value={gradeDraft[id]??g?.value??''} onChange={e=>setGradeDraft({...gradeDraft,[id]:e.target.value})}/></TableCell><TableCell><strong>{average(s,a.term)}</strong></TableCell><TableCell><button className="textbutton" disabled={saving||gradeDraft[id]===undefined||gradeDraft[id]===''} onClick={async()=>{setSaving(true);try{await persist({id,kind:'grade',studentId:s.id,assessmentId:a.id,classId:a.classId,value:gradeDraft[id]});setGradeDraft(d=>{const n={...d};delete n[id];return n});toast.success('Nota salva')}catch(e:any){toast.error(e.message)}finally{setSaving(false)}}}>Salvar nota</button></TableCell></TableRow>})}</TableBody></Table></div>{!rows.some(s=>s.kind==='student'&&s.classId===a.classId)&&<p>Esta turma ainda não tem alunos. Cadastre-os em Turmas.</p>}<p className="footnote">Média ponderada das notas já lançadas neste período, convertidas para a escala de 0 a 10. Notas em branco não entram no cálculo.</p></section>)}</>}
</>}
<footer>Seu planejamento e os registros de aprendizagem, juntos.</footer></main>
<Dialog open={!!edit} onOpenChange={open=>{if(!open&&!saving)setEdit(null)}}><DialogContent className="editor"><DialogTitle>{edit?.title?'Editar':'Novo registro de'} {names[edit?.kind||'class']}</DialogTitle><DialogDescription>Preencha os dados e salve para consultar em qualquer dispositivo.</DialogDescription>{edit&&<form onSubmit={save}>{field('title',edit.kind==='student'?'Nome do aluno':edit.kind==='class'?'Nome da turma':edit.kind==='schedule'?'Disciplina / identificação da aula':'Título','text',true)}{edit.kind==='class'?<div className="formgrid">{field('school','Escola / aulas particulares')}{field('subject','Disciplina')}{field('year','Ano letivo','number',true)}</div>:['lesson','activity'].includes(edit.kind)?<fieldset className="classtoggles"><legend>{edit.kind==='activity'?'Turmas desta atividade':'Turmas deste plano'}</legend><p className="footnote">Selecione uma ou mais turmas.</p>{classes.map(c=><label key={c.id}><Checkbox checked={(edit.classIds||[]).includes(c.id)} onCheckedChange={checked=>{const ids=checked?[...(edit.classIds||[]),c.id]:(edit.classIds||[]).filter((id:string)=>id!==c.id);setEdit({...edit,classIds:ids,classId:ids[0]||''})}}/><span>{c.title}<small>{c.school||c.subject}</small></span></label>)}</fieldset>:<label className="field">Turma<Picker label="Selecione a turma" value={edit.classId||(edit.kind==='event'?'general':'')} onChange={v=>setEdit({...edit,classId:v==='general'?'':v})} options={edit.kind==='event'?[['general','Geral — sem turma'],...classes.map(c=>[c.id,c.title] as [string,string])]:classes.map(c=>[c.id,c.title])}/></label>}
{edit.kind==='schedule'&&<><label className="field">Dia da semana<Picker label="Dia da semana" value={String(edit.day)} onChange={v=>setEdit({...edit,day:v})} options={schooldays.map((d,i)=>[String(i),d])}/></label><div className="formgrid">{field('start','Início','time',true)}{field('end','Fim','time',true)}</div>{field('room','Sala / local')}<label className="field">Exibir no quadro<Picker label="Exibir no quadro" value={edit.active||'Sim'} onChange={v=>setEdit({...edit,active:v})} options={ [['Sim','Sim'],['Não','Não — desativar horário']] }/></label></>}{!['class','student','schedule'].includes(edit.kind)&&<><div className="formgrid">{edit.kind==='activity'?<>{field('requestedDate','Data de solicitação','date',true)}{field('dueDate','Data de entrega','date',true)}</>:field('date','Data','date',true)}{edit.kind!=='assessment'&&<label className="field">Situação<Picker label="Situação" value={edit.status} onChange={v=>setEdit({...edit,status:v})} options={(edit.kind==='event'?['Planejada','Realizada','Cancelada']:['Planejada','Aplicada']).map(x=>[x,x])}/></label>}</div>{edit.kind==='event'&&field('time','Horário (opcional)','time')}{edit.kind==='assessment'&&<div className="formgrid">{field('term','Período','text',true)}{field('max','Nota máxima','number',true)}{field('weight','Peso','number',true)}</div>}{edit.kind==='lesson'&&<label className="field">Objetivos<textarea value={edit.objectives||''} onChange={e=>setEdit({...edit,objectives:e.target.value})}/></label>}<label className="field">{edit.kind==='lesson'?'Conteúdo, etapas e recursos':edit.kind==='activity'?'Descrição e orientações':edit.kind==='event'?'Descrição do evento':'Conteúdo avaliado'}<textarea rows={4} value={edit.content||''} onChange={e=>setEdit({...edit,content:e.target.value})}/></label><label className="field">Observações da aplicação<textarea value={edit.notes||''} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label></>}
<div className="formactions"><button type="button" onClick={()=>setEdit(null)} disabled={saving}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando…':'Salvar registro'}</button></div></form>}</DialogContent></Dialog>
</div>}
